<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO0E15V8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO0E15V8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO0E15V8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO0E15V8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO0E15V8\App_KernelDevDebugContainer([
    'container.build_hash' => 'O0E15V8',
    'container.build_id' => 'a9d3054e',
    'container.build_time' => 1675440709,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO0E15V8');
